### ISSUE TITLE
Add new workshop for Vaughn Vernon

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#41]
Here are the workshop details for Vaughn Vernon's workshop...use the first paragraph for the workshops page.

Title: Implementing Event-Oriented DDD

This hands-on, code-prolific, DDD workshop will teach you the essentials of how to implement using the Domain-Driven Design approach. Students will first receive an overview of DDD's strategic and tactical design, including ways to develop a Ubiquitous Language within a Bounded Context, using both Event Storming and Specification by Example.

Following this, teams of students will use these tools to reach a shared understanding of a Core Domain and Subdomains. Each team will present their "big picture" and "design level" direction and receive helpful feedback before the implementation begins. This step leads to a succession of strategic and tactical design learning and implementation steps with either Java or C#. Implementations may use Event Sourcing and traditional domain model persistence. The following will be your takeaways:

- Essential DDD, with strategic and tactical design, including developing a Ubiquitous Language in a Bounded Context
- Learn the basics of Event Storming using "big picture" and "design level" modeling
- Apply your storming results to actual implementations using Aggregates and Domain Events
- Use Domain Events to integrate with multiple Bounded Contexts
- The tradeoffs of using traditional domain model persistence and Event Sourcing

Understand that the better part of two days will be spent implementing using Java or C#. This is not a workshop for juniors, and at least 5-10 years of programming experience is recommended. You are required to supply your own computer, programming environment with build and test facilities that you use regularly, and your thinking cap.

**Comment by PowrSlave** [comment]
Done!
