### ISSUE TITLE
Update Vaughn Vernon's speaker bio

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#43]
To the following (including any existing links or formatting)...

Vaughn Vernon is a software developer and architect with more than 30 years of experience in a broad range of business domains. Vaughn is a leading expert in Domain-Driven Design and a thought leader in software simplification. He consults and teaches around Domain-Driven Design and reactive software development, helping teams and organizations realize the potential of business-driven and reactive systems as they transition from technology-driven legacy web implementation approaches. As he does so, he puts strong emphasis on embracing simplicity whenever possible. Vaughn is the author of three books: Implementing Domain-Driven Design, Reactive Messaging Patterns with the Actor Model, and Domain-Driven Design Distilled, all published by Addison-Wesley. Vaughn is also the founder of **for {comprehension}** providing consulting, live training, and online learning.

**Comment by PowrSlave** [comment]
I literally translated the for {comprehension} as it appears in this ticket, but I believe it should be a link. The original target is broken so we would need a new one.
