### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#56]
Apart from Virtual Genius (VG), we will have all new sponsors for 2018, so remove all current references to 2017 sponsors from website. This includes:

* sponsor page
* landing page slider images
* footer images

The sponsor page should be reverted back to it's first content, where it provided information about sponsorship, and a link to the 2018 sponsorship opportunities PDF document (this document will be updated as part of #61).

**Comment by PowrSlave** [comment]
Sponsors page content reverted to old copy. It just needs a reference to the upcoming PDF document and it will be good to go. I'm currently commenting out the html that references the 2017 sponsors so I can quickly plug in new 2018 sponsors and uncomment these code blocks in a much more rapid manner.

**Comment by PowrSlave** [comment]
I've essentially just commented this all out for now so it doesn't appear. Let me know if that is suitable as a temporary solution for when the 2018 sponsors are dialed in. It's easier to edit 2017 code blocks with updated info/images than to go back in the git repo history and re-grab the code blocks later.

**Comment by PowrSlave** [comment]
I actually didn't intend preemptively to close this issue. My bad.
