### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#57]
We want to get the landing page ready to announce the conference. Registration is not open yet. So this includes the following updates:

* Cityscape slider image text to have "Stay Updated" link to Newsletter form instead of "register now" link
* Remove all sliders except the main cityscape one
* Update 2018 conference and workshop dates to be "CONFERENCE September 12 - 14, 2018" and "WORKSHOPS September 11 - 12, 2018"

Main text should be:

The Explore DDD Conference sets the perfect stage to discover how industry peers and leaders are using DDD to build better software:

* World-class talks from DDD practitioners and experts.
* Two days of pre-conference full-day workshops with expert instructors.
* Blue track is dedicated to emergent exploration - unconference sessions such as impromptu modeling and coding sessions, lightning talks, and problem-solving with peers are encouraged and expected.
* A smaller (~200 attendees) conference with a real sense of community/family.
* Incredible, inspiring venue - entire 38th floor provides uninterrupted majestic views of the Rocky Mountains, downtown Denver, and city surrounds.
* Conference hotel accommodation at AAA Four Diamond Grand Hyatt Denver.

**Comment by PowrSlave** [comment]
Is the newsletter form still being created or does that link exist?

**Comment by paulrayner** [comment]
Use the same newsletter form link as before.

**Comment by PowrSlave** [comment]
Ok. newsletter link has been added.
