### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#58]
Apart from Eric Evans, we will have all new speakers for 2018, so remove all current references to 2017 speakers from website. This includes removing 2017 speakers from the:

* Speakers page
* Landing page
* All speakers pages

Eric Evan's 2018 speaker page should have its 2017 content removed, including the talks, video and the speakers list at the bottom of the page.

**Comment by PowrSlave** [comment]
I wasn't sure if I should also delete the paul rayner speaker page, so I left it, though it is currently not apparent on the current iteration of the site build
