### ISSUE TITLE
General items

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#60]
These include the following:

* Update website favicon to 2018 branding colors
* Remove "- 2017" from the title and description page metatags

**Comment by PowrSlave** [comment]
Favicon files and code assets have been created and placed. Here is what it looks like on various devices.

Bookmarked to iOS Home Screen
![favicon-ios-home-screen](https://user-images.githubusercontent.com/2702124/34635141-9ee5e044-f248-11e7-8299-f6c4ea7a91af.png)

Android Chrome
![favicon-android-chrome](https://user-images.githubusercontent.com/2702124/34635154-c5a8a3e2-f248-11e7-8c3d-e86df37ccea5.png)

Windows Metro Theme
![favicon-windows-metro](https://user-images.githubusercontent.com/2702124/34635159-ce1cfce4-f248-11e7-9f6b-1fcf4be3c30d.png)

Title and meta data updated as well.

**Comment by PowrSlave** [comment]
If there was an intended favicon design direction I am missing from the notes/chat, I can change it nearly instantaneously since the heavy lifting on creating it has already been done when I generated it in this first round.

**Comment by paulrayner** [comment]
I’d like to see what it looks like with the maze logo the same gold as on
the website, instead of white.

**Comment by PowrSlave** [comment]
Ok I will give it a try and report back.

**Comment by PowrSlave** [comment]
Favicon files updated with gold maze.
