### ISSUE TITLE
CFP page

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#62]
Provide CFP link in top menu in place of Schedule menu item to CFP page.

Content for 2018 CFP page is located in https://docs.google.com/document/d/13p_3OkM7anr3Qh9gPX3VikrSYvj6_qRLgDSULf26pEM/edit?usp=sharing.

**Comment by PowrSlave** [comment]
I've made a note that body copy text isn't going bold when it is specified. This is an SCSS dependency issue that I will fix.
