### ISSUE TITLE
Landing page - Add promo video

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#68]
Embed EDDD 2018 promo video on landing page, just above ABOUT EXPLORE DDD. I'm thinking it should be the same width as the main text below, but I'm open to other ideas on that.

Note: It should *not* auto-play. Also, is it possible to choose the frame to display? If so, it should be the last frame of the intro sequence at the 4s mark, or the very last frame of the video (1m12s?).

Video is at https://youtu.be/hIORppbgcRM.

**Comment by PowrSlave** [comment]
Video resizes to content, so that is all good, however, setting the still frame is accomplished via the video settings from the youtube account, so it will need to be adjusted there, as far as I am aware.

**Comment by paulrayner** [comment]
The video really looks great! Very happy.
