### ISSUE TITLE
Landing page - Update text

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#69]
<img width="607" alt="landing page slider text" src="https://user-images.githubusercontent.com/98950/35515003-48fb87b0-0508-11e8-8fb4-2772b365d3b6.png">

Change slider text as above, with main slider text to:

EXPLORE DDD 2018
SEPT 11-14

And (gold colored) subheading on slider text to:

CFP NOW OPEN

Where "CFP NOW OPEN" links to the CFP page.

Add new sentence to bottom of ABOUT EXPLORE DDD Section:

**Registration opens mid/late February**.

**Comment by paulrayner** [comment]
**Missing the following from the description above...**

Add new sentence to bottom of ABOUT EXPLORE DDD Section:

Registration opens mid/late February.

**Comment by PowrSlave** [comment]
I added it as a bullet item. Maybe you didn't see it there, but I can remove it from the list and put it in it's own paragraph below. I'll do that for now.

**Comment by paulrayner** [comment]
Yes, separate paragraph is what I was looking for. 💥
